### ISSUE TITLE
Specification document enhancement

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Bowie#10]
# Business case
🇬🇧
Enhance specification document at the request of some users (who could use this output format of Eno in their own process)

🇫🇷 
Révision du format spécifications (en fonction des besoins des utilisateurs dont EEC)

# Stack

## Pogues

None
## Eno
- [ ] https://github.com/InseeFr/Eno/issues/470 (EEC) - waiting for feedback)
- [ ] https://github.com/InseeFr/Eno/issues/492 (mode)
- [ ] https://github.com/InseeFr/Eno/issues/493 (externes)

## Lunatic

# Progress

WIP
# Release date

End of 2022

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Bowie/issues/69
