### ISSUE TITLE
PDF output enhancement

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Bowie#13]
# Business case
 🇬🇧
Business surveys have been using Pdf output since 2018 and improvements or evolutions have been requested, including a revision of the images called in the fo

🇫🇷 
Evolution du fo (permettant de générer les pdf) notamment pour l'affichage des images

# Stack

## Pogues
None

## Eno
https://github.com/InseeFr/Eno/issues/469
https://github.com/InseeFr/Eno/issues/490

## Lunatic

# Progress
WIP

# Release date
June 2022

**Comment by AnneHuSKa** [comment]
No longer an epic
