### ISSUE TITLE
Web : UX design approach - implementation

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Bowie#37]
# Business case
🇬🇧

Lunatic overhaul will enable the use of an external (decoupled) UI framework (ex: [Material UI](https://mui.com/)). Both Lunatic refactoring and a the work of an UX designer will lead to changes in Stromae V2.

---

🇫🇷 
La refonte de Lunatic permet de rendre possible l'utilisation d'un framework externe pour l'affichage (ex : material-UI).
Cette refonte et les travaux menés par un UXDesigner vont conduire à la révision de l'ergonomie StromaeV2.

# Stack
_here describe the impact on the product softwares, linking to related issues_

## DDI

_nothing_

## Pogues

_nothing_

## Lunatic

> link to issue

# Progress

# Release date
2023 ?

**Comment by romaintailhurat** [comment]
Will be done with Stromae V3
