### ISSUE TITLE
Pogues UX overhaul

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Bowie#39]
# Business case

🇬🇧 

Pogues has grown a lot since its first release, with a lot of new features. However, no real UX design has been made and it shows - in different ways. In 2023 we would start a UX process.

---

🇫🇷 

Pogues s'est beaucoup développé depuis sa première mise à disposition, avec de nombreuses fonctionnalités ajoutées. Cependant, aucune conception UX n'a été menée, ce qui se voit à différents endroits. En 2023 nous débuterons une démarche UX à proprement parler.

# Stack
_here describe the impact on the product softwares, linking to related issues_

## DDI
_nothing_

## Pogues
> issues to be created

## Eno
_nothing_

## Lunatic
_nothing_

# Progress
_describe progress_

# Release date
_here we want to keep track of deadlines; and provide links to milestones_

**Comment by AnneHuSKa** [comment]
Issue à créer dans Workplace si on veut faire. @JulienCarmona tu veux initier ou on attend simplement.
