### ISSUE TITLE
File upload in a questionnaire

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Bowie#47]
# Business case

🇬🇧 
Data collection through web questionnaires and file upload are currently mutually exclusive. However, there is a need to provide a file upload feature in the context of web questionnaires.

🇫🇷 
Les collectes par questionnaires et par dépôt/retrait de fichiers sont aujourd'hui orthogonales. Il existe cependant un besoin de joindre un ou plusieurs fichiers dans le cadre d'une collecte par questionnaire.

## Stakeholders

- EAP
- ECMOSS

# Stack
_here describe the impact on the product softwares, linking to related issues_

## DDI
_impact of the business case on the DDI use_

## Pogues
_link to project issues_

## Eno
_link to project issues_

## Lunatic
_link to project issues_

# Progress
_describe progress_

# Release date
_here we want to keep track of deadlines; and provide links to milestones_

**Comment by AnneHuSKa** [comment]
@JulienCarmona @lailabent Sujet Collecter. Voir si un jour la demande de upload une partie de questionnaire revient
