### ISSUE TITLE
Queen Lunatic V2 integration

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Bowie#49]
# Business case
🇫🇷 Intégration de la nouvelle version de Lunatic dans l'orchestrateur Queen.
🇬🇧 Lunatic new version integration in Queen

## Stakeholders

- Every survey team with an interviewer mode, first one being SRCV.

# Stack

## Queen

- [ ] https://github.com/InseeFr/Queen/issues/174
- [ ] https://github.com/InseeFr/Queen/issues/175
- [ ] https://github.com/InseeFr/Queen/issues/176
- [ ] https://github.com/InseeFr/Queen/issues/177
- [ ] https://github.com/InseeFr/Queen/issues/178
- [ ] https://github.com/InseeFr/Queen/issues/179
- [ ] https://github.com/InseeFr/Queen/issues/180
- [ ] https://github.com/InseeFr/Queen/issues/181
- [ ] https://github.com/InseeFr/Queen/issues/182

# Progress
_describe progress_

# Release date

Late december 2022.

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Bowie/issues/45
