### ISSUE TITLE
Public Enemy, interviewer questionnaire support

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Bowie#66]
# Business case

🇫🇷 La V1 de Public Enemy permettra la création de questionnaire pour le web. Il faudra donc développer le support des questionnaires enquêteurs (Queen).

## Stakeholders
_a list of projects / teams that expressed the business case_

- project 1
- team A

# Stack
_here describe the impact on the product softwares, linking to related issues_

## DDI
_impact of the business case on the DDI use_

## Pogues
_link to project issues_

## Eno
_link to project issues_

## Lunatic
_link to project issues_

# Progress
_describe progress_

# Release date
_here we want to keep track of deadlines; and provide links to milestones_

**Comment by AnneHuSKa** [comment]
Done
