### ISSUE TITLE
Questionnaire composition

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Bowie#7]
# Business case

🇬🇧
Historically, Pogues allow to design a standalone questionnaire, i.e. a questionnaire that exists on its own. This design principle worked until today though we find it a too restrictive. There are two main use cases that we want to address asap:

1. integrate the TCM (household shared bank of questions)
2. tendency surveys, where each month a new questionnaire is provided by composing.

:fr: [Analysis document](https://hackmd.io/@UUUhbRxkTFepqG3zY9eFsQ/HJvbvm32t), in progress.

:fr:
Historiquement, Pogues permet de concevoir un questionnaire qui existe par lui-même. Ce principe de conception a fonctionné jusqu'à aujourd'hui, mais nous le trouvons trop restrictif. Il y a deux cas d'utilisation principaux que nous voulons traiter au plus vite :
- intégrer le TCM (banque de questions partagée par les ménages)
- les enquêtes conjoncturelles, où chaque mois un nouveau questionnaire est fourni par "composition"

 
# Stack
## Pogues

- [x] https://github.com/InseeFr/Pogues/issues/558
- [x] https://github.com/InseeFr/Pogues/issues/561
- [x] https://github.com/InseeFr/Pogues/issues/597
- [x] https://github.com/InseeFr/Pogues/issues/611
- [x] https://github.com/InseeFr/Pogues/issues/615
- [x] https://github.com/InseeFr/Pogues/issues/616
- [x] https://github.com/InseeFr/Pogues/issues/617
- [ ] https://github.com/InseeFr/Pogues/issues/626
- [ ] https://github.com/InseeFr/Pogues/issues/627
- [ ] https://github.com/InseeFr/Pogues/issues/660

# Progress

An alpha version of the features has been rolled out in validation environment, this looks promising! ⭐ 

Feedback from expert designer has arrived, some features are needed (Implementing filter at the ref level, import loops for the ref questionnaire into the host questionnaire).

Since the end of February, we are in _beta test_.

**Comment by AnneHuSKa** [comment]
Migration des seules issues restantes
