### ISSUE TITLE
Install bowie on docker-compose

### ISSUE THREAD

**Issue by jeandelest** [InseeFr/Bowie#71]
# Business case
Hi Bowie Team. Am trying to install bowie through docker compose, any help will be appreciate. All bowie components (see Stack below) has been built successfully. Am still unable to get some components (pogues [ui and api], ddi and stromae v1)  working properly. I think that am missing some configurations.

# Stack
- pogues [ui and api]
- enows (core, lunatic)
- ddi services (and elasticsearch)
- Stromae (v1, v2, db)
- Postgresql

# Progress
Based on bowie install description [Bowie Install](https://github.com/InseeFr/Bowie/blob/main/GET-STARTED.md), ![Bowie Architecture](https://github.com/InseeFr/Bowie/blob/main/deploiement/bowie-archi-github.jpg), and this [file](https://github.com/InseeFr/Bowie/blob/d04cbf58c28dd8c103418704f4fae727838aaffa/deploiement/minimalist-values.yaml), I was able to make my docker compose file. All the container running without exit. 

# Issues
The following components not working and I don't have any errors in their logs: 
- Pogues (ui and api) return 404 error and Pogues (ui) has "Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data - prepareInhection.js:244:11' in the console log

The following components not working has well and their logs shows some errors:
- ddi services: Properties location [file:${catalina.base}/webapps/rmespogbo.properties] not resolvable: /usr/local/tomcat/webapps/rmespogbo.properties (No such file or directory)

- StromaeV1 return 404 error and the logs show:
org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class net.sf.ehcache.constructs.web.ShutdownListener
 java.lang.ClassNotFoundException: net.sf.ehcache.constructs.web.ShutdownListener

Thanks you for your feedbacks.

**Comment by romaintailhurat** [comment]
Hi Jean! Thank you for using our tools. 

This repo is only dedicated to the Bowie roadmap, issues are roadmap milestones, not real user issues, so i propose to move this content in the discussion panel where we would be able to answer you ASAP.

**Comment by romaintailhurat** [comment]
Discussion is here: https://github.com/InseeFr/Bowie/discussions/73
