### ISSUE TITLE
Filter in table & DynamicTable : Filter Column or Cell

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Bowie#78]
# Business case
The aim is to be able to filter (not display) a cell component of a dynamic table and a simple table.
This epic is linked to another needs : Hide Column with VTL expression.

In questionnaire designer, we have 2 level of filter
- column level
- cell level

### Proposal
![image](https://github.com/InseeFr/Bowie/assets/38245508/c12b23d8-1f2d-4715-9488-deb19516dc58)

## Stakeholders
_a list of projects / teams that expressed the business case_

- project 1
- team A

# Stack
_here describe the impact on the product softwares, linking to related issues_

## DDI
- [ ] https://github.com/InseeFr/Bowie/issues/78

## Pogues
_link to project issues_

## Eno
_link to project issues_

## Lunatic
_link to project issues_

# Progress
_describe progress_

# Release date
_here we want to keep track of deadlines; and provide links to milestones_

**Comment by BulotF** [comment]
J'ai du mal avec l'option "masquer la colonne" : on souhaite changer dynamiquement le nombre de colonnes d'un tableau ? Et donc, modifier dynamiquement la liste des en-têtes de colonnes ?

**Comment by laurentC35** [comment]
> J'ai du mal avec l'option "masquer la colonne" : on souhaite changer dynamiquement le nombre de colonnes d'un tableau ? Et donc, modifier dynamiquement la liste des en-têtes de colonnes ?

C'est le besoin en effet oui

**Comment by BulotF** [comment]
Proposition temporaire en attendant mieux : 
dans le CellLabel correspondant à la case, j'ai rajouté un : 
<r:Content textFormat="VTL">**Condition de collecte**</r:Content>

**Comment by AnneHuSKa** [comment]
@laurentC35 @lailabent @JulienCarmona : on en discute - à supprimer probablement

**Comment by JulienCarmona** [comment]
Besoin déjà exprimé avec les cases grisées. On close ce ticket car ne sera surement pas fait
