### ISSUE TITLE
Connect to the metadata repository

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Bowie#8]
# Business case

Metadata is at the core of the questionnaires created by Bowie. In the perfect settings, metadata will flow in and out of Bowie softwares by communicating with a proper metadata repository.

# Stack

## Pogues

The main impact is to develop a communication channels between Pogues and the target metadata repository.

For Insee, it means:
- developing a facade between the existing repository and Pogues (a in-house API)
- using the existing built-in solutions (Colectica API and search engine)
- a mix of both

# Progress

During the summer, progress has been made:
- the old API dev has been used for grabbing series and operations
- the built-in search API has starting to be configured for a simple use

**Comment by JulienCarmona** [comment]
On fera une Epic dans Tuleap pour ce sujet.
