### ISSUE TITLE
Dynamic table - Custom text for Add & Delete buttons

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Bowie#80]
# Business case
Custom text for add & delete buttons for DynamicTable

## Stakeholders

- Lunatic
- Lunatic-Model
- Pogues-Model
- Pogues
- Eno

# Stack
_here describe the impact on the product softwares, linking to related issues_

## DDI
- [ ] How to modelize this ?

## Pogues
_link to project issues_

## Eno
_link to project issues_

## Lunatic
- [ ]  https://github.com/InseeFr/Lunatic/issues/611

# Progress
_describe progress_

# Release date
_here we want to keep track of deadlines; and provide links to milestones_

**Comment by AnneHuSKa** [comment]
refonte POgues ?
