### ISSUE TITLE
Dynamic array : control on a line

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Bowie#94]
# Business case
There is actually no difference between a control on a line of a dynamic array and a control on the whole dynamic array.
We need something to specify that a control correspond to each line and not the whole array.

## Stakeholders
Most of business surveys

## DDI
Enrichment of d:TypeOfComputationItem : 3 new values will be added to "informational", "warning" and "stumblingblock" :
- "line-informational"
- "line-warning" 
- "line-stumblingblock"

## Pogues
https://github.com/InseeFr/Pogues/issues/724

## Pogues-model
In the complexType "ControlType", add of : xs:attribute name="scope" type="xs:string" use="optional"
In this case, it would always be "scope"="line".

## Eno
https://github.com/InseeFr/Eno/issues/920

## Lunatic-model
In the complexType "ControlType", add of : xs:attribute name="type" type="xs:string" use="optional"
In this case, it would always be "type"="line".

## Lunatic
https://github.com/InseeFr/Lunatic/pull/794

# Progress
https://github.com/InseeFr/Lunatic/issues/409

# Release date

**Comment by AnneHuSKa** [comment]
Done
