### ISSUE TITLE
Modelisation - Enhancement & Cleaning

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Bowie#95]
## Eno

- [x] InseeFr/Eno#957
- [x] InseeFr/Eno#958
- [ ] InseeFr/Eno#962
- [ ] InseeFr/Eno#961
- [x] InseeFr/Eno#960
- [x] InseeFr/Eno#959

## Lunatic

- [x] InseeFr/Lunatic#925
- [x] InseeFr/Lunatic#924
- [x] InseeFr/Lunatic#923
- [x] InseeFr/Lunatic#903
- [x] **overview**
    - [ ] InseeFr/Lunatic#921
    - [ ] InseeFr/Lunatic#920

**Comment by AnneHuSKa** [comment]
@laurentC35 : on peut clore cette "meta issue" non ? Il reste 2 sujets Eno, qui pourront faire partie d"un "refinement" ultérieur non ?

**Comment by AnneHuSKa** [comment]
On garde les 2 tickets Eno
